name: backend

on:
  push
  pull_request
  workflow_call

jobs:
  cross:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target: [i686, x86_64, arm, armhf, aarch64, mips, mipsel, mips64, mips64el, s390x, win32]
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake curl file libtool
      - name: Cross build (${{ matrix.target }})
        env:
          BUILD_TARGET: ${{ matrix.target }}
        run: cmake . && make
      - uses: actions/upload-artifact@v4
        with:
          name: QGateway-${{ matrix.target }}
          path: qcli