name: build

on:
  push:
    branches: [ "main" ]


permissions:
  contents: write

jobs:
  cross:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        target: [i686, x86_64, arm, armhf, aarch64, mips, mipsel, mips64, mips64el, s390x, win32]
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake curl file libtool
      - name: Cross build (${{ matrix.target }})
        env:
          BUILD_TARGET: ${{ matrix.target }}
        run: cmake . && make
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: 'latest'
          asset_name: QGateway-${{ matrix.target }}
          tag: ${{ github.ref }}
          overwrite: true
          body: "这是已经编译完成的版本"
          file: qcli